import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import styles from "./cards.module.css";
const resolveAssetUrl = (assetBaseUrl, path) => `${assetBaseUrl.replace(/\/$/, "")}/${path.replace(/^\//, "")}`;
const CardStyleBoundary = ({ children }) => _jsx("div", { className: styles.boundary, children: children });
export const IllustratedCard = ({ title, artworkPath, kind, layout = "full", className, assetBaseUrl = "/mighty-decks/assets", style }) => {
    const image = resolveAssetUrl(assetBaseUrl, artworkPath);
    const paper = resolveAssetUrl(assetBaseUrl, "/backgrounds/paper-with-image-shadow.png");
    const actorIcon = resolveAssetUrl(assetBaseUrl, kind === "actor" ? "/types/actor.png" : "/types/map.png");
    const compact = layout === "compact";
    return _jsx(CardStyleBoundary, { children: _jsx("article", { className: [styles.card, styles.illustrated, className].filter(Boolean).join(" "), style: style, "aria-label": title, "data-card-kind": kind, children: _jsxs("svg", { viewBox: "0 0 204 332", width: "100%", height: "100%", role: "img", "aria-label": title, children: [_jsxs("defs", { children: [_jsx("clipPath", { id: `illustrated-${kind}`, children: _jsx("rect", { x: "1", y: "1", width: "202", height: "330", rx: "11" }) }), _jsxs("linearGradient", { id: `shade-${kind}`, x1: "0", x2: "1", children: [_jsx("stop", { offset: "0", stopColor: "#101820", stopOpacity: ".74" }), _jsx("stop", { offset: ".38", stopColor: "#101820", stopOpacity: ".15" }), _jsx("stop", { offset: "1", stopColor: "#101820", stopOpacity: "0" })] })] }), _jsxs("g", { clipPath: `url(#illustrated-${kind})`, children: [kind === "actor" ? _jsx("image", { href: paper, x: "1", y: "1", width: "202", height: "330", preserveAspectRatio: "xMidYMid slice" }) : null, kind === "actor" ? _jsx("image", { href: image, x: "1", y: "1", width: "202", height: "330", preserveAspectRatio: "xMidYMid slice" }) : _jsx("image", { href: image, x: "-64", y: "64", width: "332", height: "204", transform: "rotate(90 102 166)", preserveAspectRatio: "xMidYMid slice" }), kind === "location" ? _jsx("rect", { x: "1", y: "1", width: "202", height: "62", fill: `url(#shade-${kind})` }) : null, kind === "actor" && !compact ? _jsx("image", { href: image, x: "13", y: "12", width: "30", height: "30", preserveAspectRatio: "xMidYMid meet" }) : null] }), _jsx("rect", { x: "1", y: "1", width: "202", height: "330", rx: "11", fill: "none", stroke: kind === "actor" ? "#6d5435" : "#ddcfb4", strokeWidth: "2" }), !compact ? _jsxs(_Fragment, { children: [_jsx("text", { x: kind === "location" ? "13" : "168", y: "25", textAnchor: kind === "location" ? "start" : "end", fill: kind === "location" ? "#f5ead6" : "#856a4c", style: { fontFamily: "MightyDecksShantell", fontSize: 9, fontWeight: 700 }, children: kind === "actor" ? "medieval" : title }), _jsx("text", { x: kind === "location" ? "13" : "168", y: "38", textAnchor: kind === "location" ? "start" : "end", fill: kind === "location" ? "#f5ead6" : "#856a4c", style: { fontFamily: "MightyDecksShantell", fontSize: 8, fontWeight: 700 }, children: kind === "actor" ? "Actor" : "medieval" }), _jsx("image", { href: actorIcon, x: "174", y: "11", width: "17", height: "17", preserveAspectRatio: "xMidYMid meet" })] }) : _jsxs(_Fragment, { children: [_jsx("rect", { x: "1", y: "238", width: "202", height: "93", fill: "rgba(12, 20, 27, .68)" }), _jsx("text", { x: "102", y: "278", textAnchor: "middle", fill: "#f5ead6", style: { fontFamily: "MightyDecksKalam", fontSize: 18, fontWeight: 700 }, children: kind === "location" ? title : "medieval" })] })] }) }) });
};
